import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

// Bundled by Vite as a lazy chunk (three.js comes from npm); it used to live in /public, which the
// dev server refuses to serve as a module.

// Procedural, articulated 3D avatar. Animation is presentation; neural rates drive
// only the activity indicator. Inference is performed separately in network.js.
export function createFlyScene(host,adapters={}){
const ui=adapters.root||host.parentElement;
const translate=adapters.translate||((key)=>key);const numberFormat=new Intl.NumberFormat(adapters.locale||undefined);
let disposed=false,raf=0,revealTimer=0;
const events=new AbortController();
const scene=new THREE.Scene();scene.background=new THREE.Color('#c8d5b7');scene.fog=new THREE.Fog('#c8d5b7',13,28);
const renderer=adapters.renderer||new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(36,1,.1,60);const home=new THREE.Vector3(-6.2,4.1,6.6);camera.position.copy(home);
const controls=adapters.controls||new OrbitControls(camera,renderer.domElement);controls.target.set(-.05,.85,0);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=4.2;controls.maxDistance=13;controls.maxPolarAngle=Math.PI*.49;controls.minPolarAngle=.22;controls.enablePan=false;
scene.add(new THREE.HemisphereLight('#f5ffdf','#778668',2.5));const sun=new THREE.DirectionalLight('#fff8d8',4);sun.position.set(-3,7,3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-5;sun.shadow.camera.right=5;sun.shadow.camera.top=5;sun.shadow.camera.bottom=-5;sun.shadow.normalBias=.025;scene.add(sun);const fill=new THREE.DirectionalLight('#b6d7ff',1.6);fill.position.set(3,3,-4);scene.add(fill);
const mat=(color,roughness=.5,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
const ivory=mat('#e9ebd5',.65),dark=mat('#182027',.4,.15),bodyMat=mat('#273c36',.46,.32),headMat=mat('#24362e',.35,.2),legMat=mat('#33433a',.45,.25),hairMat=mat('#14251b',.8),rubber=mat('#768679',.9),eyeMat=mat('#ba1331',.25,.12),keyMat=mat('#bbc8ab',.6),wingMat=new THREE.MeshPhysicalMaterial({color:'#c5dfd4',transparent:true,opacity:.34,roughness:.16,metalness:.2,side:THREE.DoubleSide,depthWrite:false});
function mesh(geo,material,parent=scene){const m=new THREE.Mesh(geo,material);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(w,h,d,material,x,y,z,parent=scene){const m=mesh(new THREE.BoxGeometry(w,h,d),material,parent);m.position.set(x,y,z);return m}
function ell(rx,ry,rz,material,x,y,z,parent=scene,detail=28){const m=mesh(new THREE.SphereGeometry(1,detail,Math.max(12,detail/2)),material,parent);m.scale.set(rx,ry,rz);m.position.set(x,y,z);return m}
function rod(a,b,r,material,parent=scene,r2=r*.75){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);const m=mesh(new THREE.CylinderGeometry(r2,r,a.distanceTo(b),7),material,parent);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());return m}
function line(points,color,parent=scene,opacity=1){const g=new THREE.BufferGeometry().setFromPoints(points.map(v=>new THREE.Vector3(...v)));const l=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:opacity<1,opacity}));parent.add(l);return l}
// Raised, pale desk on a quiet studio floor.
box(200,.12,200,mat('#c0ceae',1),0,-.61,0);
box(6,.18,3.65,ivory,0,.37,0);box(5.83,.1,3.47,mat('#c2c9b1',.7),0,.27,0);
for(const x of [-2.35,2.35])for(const z of [-1.25,1.25])box(.11,.8,.11,mat('#96a58c',.5,.2),x,-.09,z);
// Large desktop monitor faces the fly along -X.
const monitor=new THREE.Group();monitor.position.set(1.55,.46,-.12);monitor.rotation.y=-Math.PI/2;scene.add(monitor);
box(.88,.065,.56,dark,0,.035,-.08,monitor);box(.13,.55,.13,dark,0,.30,-.1,monitor);const monitorFrame=box(2.55,1.68,.14,dark,0,1.15,0,monitor);
const screenCanvas=document.createElement('canvas');screenCanvas.width=1024;screenCanvas.height=640;const sctx=screenCanvas.getContext('2d');const texture=new THREE.CanvasTexture(screenCanvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());const screen=mesh(new THREE.PlaneGeometry(2.37,1.48),new THREE.MeshBasicMaterial({map:texture,toneMapped:false}),monitor);screen.position.set(0,1.15,.077);screen.castShadow=false;
ell(.012,.012,.008,new THREE.MeshBasicMaterial({color:'#b6ff8d'}),.99,.365,.083,monitor,12);
// Keyboard and mouse, with individual keycaps and a fabric desk mat.
box(1.36,.018,2.35,mat('#829280',.95),.03,.47,.04);
const keyboard=new THREE.Group();keyboard.position.set(.03,.49,-.24);keyboard.rotation.y=-Math.PI/2;scene.add(keyboard);box(1.48,.08,.58,dark,0,.04,0,keyboard);
for(let row=0;row<5;row++)for(let col=0;col<14;col++){if(row===4&&col>3&&col<10)continue;const key=box(.087,.04,.078,keyMat,-.657+col*.1,.1,-.226+row*.105,keyboard);key.castShadow=false}
const space=box(.57,.04,.078,keyMat,.02,.1,.194,keyboard);const enter=box(.09,.046,.18,mat('#b9e485',.4),.657,.107,.04,keyboard);
const mouse=new THREE.Group();mouse.position.set(-.08,.5,1.02);scene.add(mouse);ell(.24,.09,.15,dark,0,.07,0,mouse);line([[-.03,.15,-.13],[-.03,.158,.13]],'#738677',mouse);box(.085,.025,.023,mat('#c3ef91',.4),.02,.159,0,mouse);
const cable=new THREE.CatmullRomCurve3([new THREE.Vector3(.16,.53,1.03),new THREE.Vector3(.64,.47,1.13),new THREE.Vector3(.97,.47,.7),new THREE.Vector3(1.1,.49,.3)]);mesh(new THREE.TubeGeometry(cable,30,.013,5,false),dark);
// Fly: six articulated legs, segmented abdomen, compound red eyes, antennae,
// transparent veined wings and sparse bristles on the thorax and legs.
const fly=new THREE.Group();fly.name='Fruit fly';fly.position.set(-1.47,1.12,.16);scene.add(fly);
const torso=new THREE.Group();fly.add(torso);const thorax=ell(.43,.37,.33,bodyMat,0,0,0,torso);thorax.rotation.z=.12;
const abdomen=ell(.62,.29,.30,bodyMat,-.67,-.015,0,torso);abdomen.rotation.z=-.08;
for(let i=0;i<5;i++){const x=-.34-i*.17;const t=(x+.67)/.62;const rad=Math.sqrt(Math.max(.03,1-t*t));const ring=mesh(new THREE.TorusGeometry(.29*rad,.017,5,36),mat(i%2?'#899079':'#141f1b',.6,.1),torso);ring.rotation.y=Math.PI/2;ring.position.set(x,-.015,0);ring.scale.y=.94}
ell(.12,.14,.14,headMat,-1.2,-.07,0,torso);
const head=new THREE.Group();head.position.set(.40,.06,0);torso.add(head);ell(.29,.29,.275,headMat,.04,0,0,head);
for(const side of [-1,1]){const eye=ell(.245,.25,.105,eyeMat,.105,.025,side*.246,head,40);eye.rotation.y=side*.23;const facetGeo=new THREE.SphereGeometry(.012,5,3);const facetMat=mat('#e13a49',.37,.1);const facets=new THREE.InstancedMesh(facetGeo,facetMat,110);const o=new THREE.Object3D();let k=0;for(let iy=0;iy<10;iy++)for(let ix=0;ix<11;ix++){const u=(ix-5+.5*(iy%2))/.5/11,v=(iy-4.5)/5;if(u*u+v*v>.91){o.position.set(0,0,0);o.scale.setScalar(0)}else{o.position.set(.105+.235*u,.025+.24*v,side*(.251+.097*Math.sqrt(1-u*u-v*v)));o.scale.set(1,.8,.38)}o.updateMatrix();facets.setMatrixAt(k++,o.matrix)}head.add(facets);const a=[.18,.21,side*.085],b=[.31,.31,side*.13],c=[.35,.37,side*.22];rod(a,b,.027,headMat,head);ell(.04,.06,.035,headMat,...b,head,14);rod(b,c,.009,hairMat,head);for(let q=0;q<3;q++)rod([c[0],c[1]-.03*q,c[2]],[c[0]+.055,c[1]+.035-.02*q,c[2]+side*.04],.003,hairMat,head)}
ell(.10,.15,.095,mat('#53604b',.5),.23,-.21,0,head);rod([.28,-.22,0],[.39,-.29,0],.022,headMat,head);
// Stable pseudo-random distribution, independent from game/model data.
let seed=73;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}
for(let i=0;i<90;i++){const theta=rand()*Math.PI*2,phi=rand()*Math.PI*.65;const x=.40*Math.sin(phi)*Math.cos(theta),y=.35*Math.cos(phi),z=.32*Math.sin(phi)*Math.sin(theta);rod([x,y,z],[x*1.13,y+.055+rand()*.065,z*1.15],.0035,hairMat,torso,.001)}
const wings=[];for(const side of [-1,1]){const wing=new THREE.Group();wing.position.set(-.12,.29,side*.16);wing.rotation.y=side*.12;torso.add(wing);const outline=[[0,0,0],[-.5,.005,side*.11],[-1.30,.02,side*.23],[-1.60,.01,side*.48],[-1.48,0,side*.67],[-1.1,-.01,side*.70],[-.55,0,side*.46],[-.12,0,side*.13]];const verts=[];for(let i=1;i<outline.length-1;i++)verts.push(...outline[0],...outline[i],...outline[i+1]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.computeVertexNormals();const skin=mesh(g,wingMat,wing);skin.castShadow=false;line([...outline,outline[0]],'#5c7d6c',wing,.55);for(const p of [outline[2],outline[3],outline[4],outline[5]])line([[0,.005,0],[-.6,.012,side*.27],p],'#5c7d6c',wing,.5);line([[-.48,.014,side*.20],[-.65,.014,side*.50]],'#5c7d6c',wing,.4);line([[-.98,.015,side*.27],[-1.12,.015,side*.65]],'#5c7d6c',wing,.4);wings.push(wing)}
const legs=[];for(const side of [-1,1])for(let n=0;n<3;n++){const anchor=[.24-n*.27,-.16,side*.23];const elbow=[n===0?.54:n===1?-.10:-.71,-.34,side*.57];const foot=[n===0?1.19:n===1?-.12:-1.06,-.65,side*(n===0?.37:.85)];if(n===0&&side===1){foot[0]=1.32;foot[1]=-.48;foot[2]=.87}const group=new THREE.Group();fly.add(group);const upper=rod(anchor,elbow,.043,legMat,group,.031),lower=rod(elbow,foot,.025,legMat,group,.012);const toe=rod(foot,[foot[0]+.12,foot[1]-.025,foot[2]+side*.035],.012,hairMat,group,.006);ell(.048,.048,.048,legMat,...elbow,group,12);for(let j=1;j<5;j++){const t=j/5;const p=elbow.map((v,i)=>v*(1-t)+foot[i]*t);rod(p,[p[0]-.03,p[1]+.025,p[2]+side*.045],.0035,hairMat,group,.001)}legs.push({group,n,side,upper,lower,toe})}
// A slim desk light, matching the reference's small laboratory setting.
const lamp=mat('#81977c',.35,.3);box(.45,.04,.38,lamp,2.2,.49,-1.26);rod([2.2,.5,-1.26],[2.2,2.6,-1.26],.025,lamp);rod([2.2,2.6,-1.26],[.2,2.6,-1.26],.025,lamp);box(.40,.065,.14,lamp,.14,2.6,-1.26);box(.32,.012,.11,new THREE.MeshBasicMaterial({color:'#ffffc6'}),.14,2.56,-1.26);
let game=null,pred=null,revealed=false,phase='waiting',phaseStarted=performance.now(),paused=matchMedia('(prefers-reduced-motion: reduce)').matches,meanActivity=.0,lastFrame=0,phaseTime=0,image=null,imageGeneration=0;
function wrapText(text,x,y,maxWidth,size,maxLines=3){sctx.font=`700 ${size}px system-ui`;const words=String(text).split(' ');let line='',lines=0;for(const word of words){const test=line?line+' '+word:word;if(sctx.measureText(test).width>maxWidth&&line){sctx.fillText(line,x,y);line=word;y+=size*1.22;if(++lines>=maxLines)return y}else line=test}sctx.fillText(line,x,y);return y+size*1.22}
function screenDraw(){sctx.fillStyle='#0b151e';sctx.fillRect(0,0,1024,640);sctx.fillStyle='#1b3141';sctx.fillRect(0,0,1024,58);sctx.fillStyle='#82cef3';sctx.font='700 22px system-ui';sctx.fillText('STEAMGUESSR',35,38);sctx.fillStyle='#a6b6c0';sctx.font='18px system-ui';sctx.fillText('FLY PLAYER / 01',760,37);if(image){sctx.drawImage(image,30,83,440,206)}else{sctx.fillStyle='#213f4b';sctx.fillRect(30,83,440,206);sctx.fillStyle='#91bac6';sctx.font='700 34px system-ui';sctx.fillText('STEAM',167,194)}sctx.fillStyle='#edf4f7';wrapText(game?.name||translate('fly.screenNew'),501,113,486,32,3);sctx.fillStyle='#87a7b8';sctx.font='18px system-ui';const tags=(game?.tags||[]).slice(0,3).join(' / ');sctx.fillText(tags.slice(0,50),36,325);sctx.fillText(`${game?.year||'—'}   ·   ${(game?.dev||[]).join(', ').slice(0,65)}`,36,357);sctx.fillStyle='#132832';sctx.fillRect(30,390,964,216);sctx.fillStyle='#c1ed82';sctx.font='bold 23px system-ui';sctx.fillText(translate(revealed?'fly.screenGuess':'fly.screenQuestion'),57,432);sctx.fillStyle='#edf4f7';sctx.font='bold 52px monospace';sctx.fillText(revealed&&pred?numberFormat.format(pred.reviews):'••• •••',57,505);sctx.font='22px system-ui';sctx.fillStyle='#8eb8c8';sctx.fillText(revealed&&pred?translate('fly.screenPositive',{p:pred.pct}):translate(phase==='typing'?'fly.screenTyping':'fly.screenHidden'),58,553);sctx.fillStyle='#82ae5c';sctx.fillRect(746,467,200,78);sctx.fillStyle='#122216';sctx.font='bold 23px system-ui';sctx.fillText(translate(revealed?'fly.screenDone':'fly.screenAnswer'),770,515);texture.needsUpdate=true}
function setPhase(p){phase=p;phaseStarted=performance.now();phaseTime=0;ui.querySelector('#scene-status').textContent=translate('fly.phase.'+p);screenDraw()}
function setGame(g){clearTimeout(revealTimer);game=g;pred=null;revealed=false;image=null;imageGeneration++;const token=imageGeneration;ui.querySelector('#scene-readout').textContent=translate('fly.hidden');setPhase('waiting');const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{if(!disposed&&token===imageGeneration){image=img;screenDraw()}};img.onerror=()=>{};img.src=g.img;screenDraw()}
function setPrediction(p){pred=p;meanActivity=p.state.reduce((a,b)=>a+b,0)/p.state.length;ui.querySelector('#scene-activity').textContent=meanActivity.toFixed(3);ui.querySelector('#scene-cell-count').textContent=translate('fly.units',{n:p.state.length});setPhase('ready')}
function reveal(p,humanScore,flyScore){pred=p;revealed=true;ui.querySelector('#scene-readout').textContent=translate('fly.guessFormat',{n:numberFormat.format(p.reviews),p:p.pct});setPhase('typing');revealTimer=setTimeout(()=>{if(!disposed&&revealed)setPhase(flyScore>humanScore?'win':flyScore<humanScore?'lose':'tie')},1450)}
function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}const ro=new ResizeObserver(resize);ro.observe(host);
function reset(){camera.position.copy(home);controls.target.set(-.05,.85,0);controls.update()}
function pause(){paused=!paused;const b=ui.querySelector('#scene-motion');b.textContent=paused?'▶':'Ⅱ';b.setAttribute('aria-label',translate(paused?'fly.resume':'fly.pause'));return paused}
ui.querySelector('#scene-motion').textContent=paused?'▶':'Ⅱ';ui.querySelector('#scene-motion').addEventListener('click',pause,{signal:events.signal});ui.querySelector('#scene-reset').addEventListener('click',reset,{signal:events.signal});ui.querySelector('#scene-expand').addEventListener('click',async()=>{const panel=ui;try{if(document.fullscreenElement)await document.exitFullscreen();else if(panel.requestFullscreen)await panel.requestFullscreen();else panel.classList.toggle('expanded')}catch{panel.classList.toggle('expanded')}},{signal:events.signal});
window.addEventListener('keydown',e=>{if(e.key==='Escape')ui.classList.remove('expanded')},{signal:events.signal});
function frame(now){if(disposed)return;raf=requestAnimationFrame(frame);const dt=Math.min(.05,(now-lastFrame)/1000||0);lastFrame=now;if(document.hidden||host.offsetParent===null)return;controls.update();if(!paused){phaseTime+=dt;const t=now/1000;torso.position.y=Math.sin(t*2.1)*.007;head.rotation.z=Math.sin(t*.9)*.035;head.rotation.y=Math.sin(t*.63)*.06;wings.forEach((wing,i)=>{const sign=i===0?-1:1;wing.rotation.x=sign*(.025+Math.sin(t*2.3)*.015);if(phase==='win'&&phaseTime<2.2)wing.rotation.x+=sign*Math.sin(t*35)*.30});legs.forEach(l=>{l.group.rotation.z=0;if(l.n===0&&phase==='typing')l.group.rotation.z=Math.sin(t*18+l.side)*.035;if(l.n===0&&phase==='ready')l.group.rotation.z=Math.sin(t*1.5+l.side)*.006;if(l.n===0&&phase==='win'&&phaseTime<1.8)l.group.rotation.z=.13+Math.sin(t*7)*.08});if(phase==='lose'&&phaseTime<2.5)head.rotation.z=-.15;}
renderer.render(scene,camera)}screenDraw();resize();raf=requestAnimationFrame(frame);
function dispose(){if(disposed)return;disposed=true;imageGeneration++;clearTimeout(revealTimer);cancelAnimationFrame(raf);events.abort();ro.disconnect();controls.dispose();const geometries=new Set(),materials=new Set();scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m)}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());texture.dispose();renderer.dispose();renderer.forceContextLoss?.();renderer.domElement.remove();}
return{dispose,setGame,setPrediction,reveal,pause,reset,meanActivity:()=>meanActivity,renderer,scene};
}
